### ISSUE TITLE
Service 'imagist.tracy.bar' not found

### ISSUE THREAD

**Issue by PavelJurasek** [contributte/imagist#12]
Hi,

v1.0 ends up with `Nette\DI\MissingServiceException: Service 'imagist.tracy.bar' not found.` if `EventSubscriberInterface` is not found. Later on it is not checked whether imagist.tracy.bar is registered.

Master version implements such `Symfony\Component\EventDispatcher\EventSubscriberInterface`, but symfony/event-dispatcher is not explicitly listed in composer requirements (installed in dev dependencies via codeception/codeception package) and therefore app crashes again.

**Comment by MartkCz** [comment]
Hi, did you try dev-master? commit https://github.com/contributte/imagist/commit/82f1d8d028c00716a258eab76fe6cb0125720092 probably fixed it. I'll try to remove symfony dependency from tracy bar.

**Comment by PavelJurasek** [comment]
Since I don't have any package that would depend on sf/event-dispatcher and I don't have it installed myself, then I get the following error: `Service 'imagist.tracy.bar': Interface "Symfony\Component\EventDispatcher\EventSubscriberInterface" not found`.

**Comment by MartkCz** [comment]
Thank you for information. I will send PR. Temporary workaround could be `$builder->removeDefinition('imagist.tracy.bar')`
